version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: connected_repo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: connected_repo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: