import { apiProductRequestStatusZod, apiRequestMethodZod } from "@zod-schemas/enums.zod";
import { zSmallint, zString, zTimestamps } from "@zod-schemas/zod_utils";
import z from "zod";

const apiProductRequestLogAutoGeneratedZod = z.object({
  apiProductRequesId: z.ulid(),
});

const apiProductRequestLogMandatoryZod = z.object({
  teamId: z.uuid(),
  teamUserReferenceId: zString,
  method: apiRequestMethodZod,
  path: zString,
  ip: zString,
  status: apiProductRequestStatusZod,
});

const apiProductRequestOptionalZod = z.object({
  requestBodyText: zString,
  requestBodyJson: z.json(),
  responseText: zString,
  responseJson: z.json(),
  responseTimeMs: zSmallint(0),
});

export const apiProductRequestLogCreateInputZod = apiProductRequestLogMandatoryZod.extend(apiProductRequestOptionalZod.partial().shape);
export type ApiProductRequestLogCreateInput = z.infer<typeof apiProductRequestLogCreateInputZod>;

export const apiProductRequestLogUpdateInputZod = apiProductRequestLogMandatoryZod.extend(apiProductRequestOptionalZod.shape).extend(zTimestamps).partial();
export type ApiProductRequestLogUpdateInput = z.infer<typeof apiProductRequestLogUpdateInputZod>;

export const apiProductRequestLogSelectAllZod = apiProductRequestLogMandatoryZod.extend(apiProductRequestOptionalZod.shape).extend(zTimestamps).extend(apiProductRequestLogAutoGeneratedZod.shape);
export type ApiProductRequestLogSelectAll = z.infer<typeof apiProductRequestLogSelectAllZod>;

export const apiProductRequestLogGetByIdInputZod = z.object({
  apiProductRequestId: z.string(),
});