import { apiProductSkuZod } from "@zod-schemas/enums.zod";
import { webhookCallQueueSelectAllZod } from "@zod-schemas/webhook_call_queue.zod";
import { zSmallint, zString, zTimeEpoch } from "@zod-schemas/zod_utils";
import z from "zod";

const subscriptionAutoGeneratedZod = z.object({
  subscriptionId: z.ulid(),
});

const subscriptionMandatoryZod = z.object({
  expiresAt: zTimeEpoch,
  maxRequests: zSmallint(0),
  apiProductSku: apiProductSkuZod,
  requestsConsumed: zSmallint(0).default(0),
  teamId: z.uuid(),
  teamUserReferenceId: zString,
});

const subscriptionOptionalZod = z.object({
  billingInvoiceNumber: zString.nullable(),
  billingInvoiceDate: zTimeEpoch.nullable(),
  paymentReceivedDate: zTimeEpoch.nullable(),
  paymentTransactionId: zString.nullable(),
});

export const subscriptionRelationsZod = z.object({
  webHooksCalled: z.array(webhookCallQueueSelectAllZod).nullable(),
});

export const subscriptionCreateInputZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.partial().shape);
export type SubscriptionCreateInput = z.infer<typeof subscriptionCreateInputZod>;

export const subscriptionUpdateInputZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.shape).extend(subscriptionRelationsZod.partial());
export type SubscriptionUpdateInput = z.infer<typeof subscriptionUpdateInputZod>;

export const subscriptionSelectAllZod = subscriptionMandatoryZod.extend(subscriptionOptionalZod.shape).extend(subscriptionRelationsZod.shape).extend(subscriptionAutoGeneratedZod.shape);
export type SubscriptionSelectAll = z.infer<typeof subscriptionSelectAllZod>;

export const subscriptionGetByIdInputZod = z.object({
  subscriptionId: z.string(),
});