import { webhookStatusZod } from "@zod-schemas/enums.zod";
import { zSmallint, zString, zTimeEpoch, zTimestamps } from "@zod-schemas/zod_utils";
import z from "zod";

const webhookCallQueueAutoGeneratedZod = z.object({
  webhookCallQueueId: z.ulid(),
});

const webhookCallQueueMandatoryZod = z.object({
  teamId: z.uuid(),
  webhookUrl: z.url(),
  payload: z.json(),
  status: webhookStatusZod,
  attempts: zSmallint().positive().default(0),
  maxAttempts: zSmallint().positive().default(3),
  scheduledFor: zTimeEpoch,
  subscription_id: z.ulid(),
});

const webhookCallQueueOptionalZod = z.object({
  lastAttemptAt: zTimeEpoch.nullable(),
  sentAt: zTimeEpoch.nullable(),
  errorMessage: zString.nullable(),
});

export const webhookCallQueueCreateInputZod = webhookCallQueueMandatoryZod.extend(webhookCallQueueOptionalZod.partial().shape);
export type WebhookCallQueueCreateInput = z.infer<typeof webhookCallQueueCreateInputZod>;

export const webhookCallQueueUpdateInputZod = webhookCallQueueMandatoryZod.extend(webhookCallQueueOptionalZod.shape).extend(zTimestamps).partial();
export type WebhookCallQueueUpdateInput = z.infer<typeof webhookCallQueueUpdateInputZod>;

export const webhookCallQueueSelectAllZod = webhookCallQueueMandatoryZod.extend(webhookCallQueueOptionalZod.shape).extend(zTimestamps).extend(webhookCallQueueAutoGeneratedZod.shape);
export type WebhookCallQueueSelectAll = z.infer<typeof webhookCallQueueSelectAllZod>;

export const webhookCallQueueGetByIdInputZod = z.object({
  webhookCallQueueId: z.string(),
});